# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20171120_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
